import { IS_LINUX, IS_MAC } from "@/lib/platform";

/**
 * Cross-platform (macOS / Linux / typical Unix userland) shell commands.
 * Lowercase; multi-word commands are fine (ranked by first-character prefix).
 */
const UNIVERSAL: readonly string[] = [
  // a
  "alias",
  "awk '{print $1}'",
  // b
  "bash",
  "bg",
  "builtin",
  "bind",
  // c
  "cat",
  "cd",
  "cd ..",
  "chmod +x",
  "chown",
  "comm",
  "cmp",
  "cp",
  "curl -O",
  "cut -d:",
  "cargo build",
  "cargo run",
  "cargo test",
  "cargo clippy",
  "clear",
  "crontab -l",
  // d
  "date",
  "diff",
  "dig",
  "dirname",
  "docker ps",
  "docker images",
  "docker compose up",
  "docker compose down",
  "docker logs",
  "du -sh",
  // e
  "echo",
  "env",
  "eval",
  "exec",
  "exit",
  "export",
  // f
  "false",
  "fg",
  "file",
  "find . -name",
  "fmt",
  // g
  "git status",
  "git diff",
  "git log",
  "git pull",
  "git push",
  "git checkout",
  "git branch",
  "git commit",
  "git add",
  "git clone",
  "git merge",
  "git rebase",
  "grep -r",
  "groups",
  "gzip",
  // h
  "head",
  "history",
  "host",
  "hostname",
  "htop",
  // i
  "id",
  "ifconfig",
  "install",
  // j
  "java -version",
  "jobs",
  "join",
  // k
  "kill",
  "killall",
  "kubectl get pods",
  "kubectl get svc",
  "kubectl logs",
  // l
  "less",
  "ln -s",
  "local",
  "logout",
  "ls",
  "ls -la",
  // m
  "make",
  "man",
  "mkdir",
  "more",
  "mount",
  "mktemp",
  "mv",
  // n
  "nano",
  "nice",
  "nl",
  "node",
  "npm install",
  "npm run dev",
  // o
  "od",
  "openssl version",
  "openssl s_client -connect",
  // p
  "patch",
  "pgrep",
  "ping -c 4",
  "pnpm install",
  "pnpm dev",
  "pnpm run",
  "popd",
  "ps aux",
  "pushd",
  "pwd",
  "python3",
  "pip install",
  // q
  "quota -s",
  "quota -v",
  // r
  "read",
  "rev",
  "rm",
  "rmdir",
  "rsync -av",
  "rustc",
  // s
  "scp",
  "sed -n '1,20p'",
  "sh -c",
  "sleep",
  "sort",
  "split",
  "ssh",
  "stat",
  "sudo",
  // t
  "tail",
  "tail -f",
  "tar -xvf",
  "tar -czvf",
  "tee",
  "timeout",
  "tmux",
  "top",
  "touch",
  "tr",
  "true",
  "type",
  // u
  "uname -a",
  "unalias",
  "unexpand",
  "uniq",
  "unlink",
  "unzip",
  "uptime",
  "users",
  // v
  "vi",
  "vim",
  "view",
  // w
  "wait",
  "watch",
  "wc -l",
  "wget",
  "which",
  "who",
  "whoami",
  // x
  "xargs",
  "xxd",
  "xz",
  // y
  "yarn install",
  "yes",
  "yq",
  // z
  "zcat",
  "zgrep",
  "zip",
  "zsh",
];

/** macOS-specific (BSD userland, Homebrew, Apple tools). */
const MACOS_EXTRA: readonly string[] = [
  "arch",
  "at",
  "autossh",
  "brew install",
  "brew upgrade",
  "brew doctor",
  "brew services list",
  "diskutil list",
  "defaults read",
  "mdfind",
  "networksetup -listallnetworkservices",
  "open .",
  "open -a",
  "pbcopy",
  "pbpaste",
  "say",
  "softwareupdate -l",
  "sw_vers",
  "sysctl -a",
  "screencapture",
  "security find-identity",
  "dscl . -list",
  "plutil -lint",
  "xcrun",
  "xcode-select --install",
  "log show --predicate",
  "jot",
  "qlmanage -p",
];

/** Linux-specific (GNU userland, systemd, apt/dnf, iproute2). */
const LINUX_EXTRA: readonly string[] = [
  "apt update",
  "apt install",
  "apt search",
  "apt-cache search",
  "apt-get update",
  "dpkg -l",
  "dnf install",
  "yum install",
  "systemctl status",
  "systemctl list-units",
  "journalctl -xe",
  "journalctl -u",
  "ip addr",
  "ip route",
  "ss -tlnp",
  "useradd",
  "usermod",
  "passwd",
  "chpasswd",
  "snap list",
  "lsof -i",
  "lsblk",
  "free -h",
  "vmstat",
  "iostat",
  "sar",
  "getent passwd",
  "xdg-open",
  "update-alternatives --display",
  "qemu-img info",
];

function buildStaticList(): readonly string[] {
  const merged = [...UNIVERSAL];
  if (IS_MAC) merged.push(...MACOS_EXTRA);
  if (IS_LINUX) merged.push(...LINUX_EXTRA);
  return merged;
}

export const STATIC_COMMAND_LINES: readonly string[] = buildStaticList();
